### ISSUE TITLE
Add shadow to calculator

### ISSUE THREAD

**Issue by natesabrown** [pgosar/Open-Source-Contributions#19]
Add a little shadow to the calculator to show that we haven't fully abandoned our love affair with digital skeuomorphism. This could be done by placing a `box-shadow` property on the `table` in the `styles.css` file. Try to make the shadow not to dark, not too light, but jusssst right. 🐻

**Comment by AkshadK7** [comment]
Can I be assigned this issue for a Hacktoberfest PR ?

P.S:  You can always check out my Web Dev skills through my Github profile :)
