### ISSUE TITLE
Add link to GitHub at bottom

### ISSUE THREAD

**Issue by natesabrown** [pgosar/Open-Source-Contributions#20]
Add a link to the GitHub repo at the bottom of the page. Should be fairly small and it would be even better if you can use the octocat logo instead of just words that say "github". When you click on it it should take you to this github repository so other people can contribute to this lit calculator.

**Comment by AkshadK7** [comment]
Can I be assigned this issue for a Hacktoberfest PR ?

P.S:  You can always check out my Web Dev skills through my Github profile :)

**Comment by AkshadK7** [comment]
Can I be assigned this issue for a Hacktoberfest PR ?

P.S:  You can always check out my Web Dev skills through my Github profile :)
